### PR TITLE
feat: use Promise.resolve() with ternary operator

### PR DESCRIPTION
**Pull request by thgreasi**
Related to #5. This might give some speed-up.

### CODE REVIEW

**Comment by mmahalwy** [comment]
looking good

**Comment by thgreasi** [comment]
@mmahalwy Just pushed a new version with some test cases and merged into master.
If you have some time can you please give it a try?
I introduced a change regarding the way that external module imports are detected and resolved.

**Comment by mmahalwy** [comment]
@thgreasi will do this week! :)

**Comment by mmahalwy** [comment]
Thanks so much! This is awesome <3

**Pull request merged**
