### PR TITLE
Added travis ci support for stable node version

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by thgreasi** [comment]
Thanks :)

**Comment by amilajack** [comment]
@thgreasi also remember to enable tests at travis-ci.org

**Comment by thgreasi** [comment]
Don't they run out of the box? Do I need to do anything manually?

**Comment by amilajack** [comment]
By default, travis ci tests are off. They have to be enabled manually at the website :( kind of sucks. Should be automatic.

**Pull request merged**
